spring.application.name=labgeneral-ai-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/labgeneral
spring.datasource.username=labgeneral
spring.datasource.password=labgeneral
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8081

openai.base-url=https://api.groq.com/openai/v1
openai.api-key=${GROQ_API_KEY}
openai.model=llama-3.3-70b-versatile

rag.service.url=http://localhost:8000